apiVersion: v1
kind: Namespace
metadata:
  name: aks-gpu
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-gpu-daemonset
  namespace: aks-gpu
spec:
  selector:
    matchLabels:
      app: aks-gpu-daemonset
  template:
    metadata:
      labels:
        app: aks-gpu-daemonset
    spec:
      initContainers:
      - name: aks-gpu-daemonset
        image: ubuntu:24.10
        command:
        - nsenter
        - --target
        - "1"
        - --mount
        - --uts
        - --ipc
        - --net
        - --pid
        - --
        - bash
        - -exc
        - |
          set -x
          set -e
          set -o pipefail
          if [ -f /etc/aks-gpu-daemonset/donefile ]; then
            echo "aks-gpu-daemonset already done, exit"
            exit 0
          fi
          add-apt-repository ppa:canonical-kernel-team/ppa
          apt-get update
          apt-get install -y linux-azure-nvidia
          cat <<EOF | tee -a /etc/default/grub.d/60-azure-nvidia.cfg
          GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX console=tty1 console=ttyAMA0 earlycon=pl011,0xeffec000 initcall_blacklist=arm_pmu_acpi_init nvme_core.io_timeout=240 iommu.passthrough=1 irqchip.gicv3_nolpi=y nvidia.NVreg_NvLinkDisable=0 arm_smmu_v3.disable_msipolling=1"
          EOF
          sed -i 's|^GRUB_DEFAULT=0|#GRUB_DEFAULT=0\nGRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux 6.8.0-1016-azure-nvidia"|' /etc/default/grub
          sed -i 's|GRUB_TIMEOUT=0|GRUB_TIMEOUT=5|' /etc/default/grub
          update-grub
          echo "blacklist nouveau " | tee -a /etc/modprobe.d/blacklist.conf
          update-grub
          echo "done... writing donefile"
          mkdir -p /etc/aks-gpu-daemonset
          touch /etc/aks-gpu-daemonset/donefile
          echo "donefile created"
          echo "rebooting in 5 seconds..."
          sleep 5
          reboot
        securityContext:
          privileged: true
      containers:
      - name: is-it-done
        image: ubuntu:24.10
        command:
        - nsenter
        - --target
        - "1"
        - --mount
        - --uts
        - --ipc
        - --net
        - --pid
        - --
        - bash
        - -exc
        - |
          set -x
          set -e
          set -o pipefail
          if [ ! -f /etc/aks-gpu-daemonset/donefile ]; then
            echo "aks-gpu-daemonset not done, exit"
            exit 1
          fi
          echo "aks-gpu-daemonset done, exit"
        securityContext:
          privileged: true
      hostNetwork: true
      hostPID: true
      hostIPC: true
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
      terminationGracePeriodSeconds: 30
